<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../RegistryServices/RegistryServices.csproj" />
    <ProjectReference Include="..\..\..\src\ServiceRegistryModules.Core\ServiceRegistryModules.Core.csproj" />
    <ProjectReference Include="..\TestSamples1\TestSamples1.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.3" />
  </ItemGroup>

</Project>
