<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../RegistryServices/RegistryServices.csproj" />
    <ProjectReference Include="..\..\..\src\ServiceRegistryModules.Abstractions\ServiceRegistryModules.Abstractions.csproj" />
  </ItemGroup>

</Project>
